{{- if .Values.dnsProber.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "custom-rhcl-console.dnsProber" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "custom-rhcl-console.labels" . | nindent 4 }}
    {{- include "custom-rhcl-console.dnsProberSelectorLabels" . | nindent 4 }}
{{- end }}
